# Generated by Django 5.0.3 on 2024-03-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250, verbose_name='Источник')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('tone', models.CharField(max_length=50, verbose_name='Тональность')),
                ('date', models.DateTimeField(verbose_name='Дата анализа')),
            ],
        ),
    ]
