# Generated by Django 5.0.3 on 2024-04-06 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='query',
            field=models.CharField(default='non', max_length=250, verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='source',
            field=models.CharField(default='client', max_length=250, verbose_name='Источник'),
        ),
    ]
