# Generated by Django 5.0.3 on 2024-04-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_texts', '0002_articles_query_alter_articles_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='query',
            field=models.CharField(default='client', max_length=250, verbose_name='Запрос'),
        ),
    ]
