# Generated by Django 5.0.3 on 2024-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_texts', '0003_alter_articles_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text_id',
            field=models.IntegerField(default=0, verbose_name='ID текста'),
        ),
    ]
